[[project]]
name = "TARS"
date = "2019–"
desc = """
social media promotion automator via IRC interface"""
[[project.link]]
name = "check it out"
href = "/tars/help"

[[project]]
name = "cluedo"
date = "2019–"
desc = """
browser-based offset-multiplayer game, like Moirai"""
[[project.link]]
name = "check it out"
href = "/cluedo"
