[[project]]
name = "Faux Coffee Shop"
date = [[2017]]
tags = ["completed"]
tech = ["JavaScript", "AngularJS"]
desc = """
a neograph based loosely on the Coffee Shop Code"""
[[project.link]]
name = "check it out"
href = "/neograph"

[[project]]
name = "The Pipeworks"
date = [[2016], [2017]]
tags = ["completed"]
tech = ["Spreadsheets", "Fiction"]
desc = """
dystopian-themed online board game"""
[[project.link]]
name = "board"
href = "https://docs.google.com/spreadsheets/d/1G0XCT7KVrhxvwK1Tv-7TBZiYjiwX9NlSijeQNuWlEec/edit?usp=sharing"
[[project.link]]
name = "rules"
href = "https://docs.google.com/document/d/1Dwu1WJfo7OCM7y66ucyw6y37SK-96s2T4UIwTDTBZaQ/edit?usp=sharing"

[[project]]
name = "SCP-3939"
date = [[2018]]
tags = ["completed"]
tech = ["Fiction"]
desc = """
a multiple choice story published on the SCP Foundation"""
[[project.link]]
name = "check it out"
href = "http://scp-wiki.net/scp-3939"

[[project]]
name = "SCP-3211"
date = [[2018]]
tags = ["completed"]
tech = ["Fiction", "JavaScript", "jQuery"]
desc = """
text-based antimeme simulator"""
[[project.link]]
name = "check it out"
href = "http://scp-wiki.net/scp-3211"

[[project]]
name = "Text gradient generator"
date = [[2018]]
tags = ["completed"]
tech = ["JavaScript", "AngularJS"]
desc = """
browser-based tool for making textual BBCode gradients"""
[[project.link]]
name = "check it out"
href = "/text-gradient"

[[project]]
name = "Black Highlighter"
date = [[2019]]
tags = ["completed"]
tags = ["CSS", "Gulp.js"]
desc = """
modernised CSS theme for SCP wiki"""
[[project.link]]
name = "check it out"
href = "https://github.com/Nu-SCPTheme/Black-Highlighter"

[[project]]
name = "Regex Series Replace"
date = [[2020]]
tags = ["completed", "utility"]
tags = ["TypeScript", "Vue", "Webpack"]
desc = """
browser-based tool for sharing a regex replacment series"""
[[project.link]]
name = "check it out"
href = "/series-replace"

[[project]]
name = "SCUTTLE API wrapper"
date = [[2020]]
tags = ["completed", "utility"]
tech = ["Python"]
desc = """
Python wrapper around SCUTTLE API"""
[[project.link]]
name = "check it out"
href = "https://pypi.org/project/python-scuttle"
[[project.link]]
name = "SCUTTLE"
href = "https://github.com/scuttle/scuttle"

[[project]]
name = "Ur"
date = [[2020]]
tags = ["completed"]
tech = ["TypeScript", "SVG", "GitHub Actions"]
desc = """
The Royal Game of Ur, on my GitHub profile"""
[[project.link]]
name = "check it out"
href = "https://github.com/rossjrw/rossjrw"



[[project]]
name = "TARS"
date = [[2019]]
tags = ["working"]
tech = ["Python"]
desc = """
social media promotion automator via IRC interface"""
[[project.link]]
name = "check it out"
href = "/tars/help"

[[project]]
name = "Gallifreyo"
date = [[2017, 2018], [2020]]
tags = ["working"]
tech = ["TypeScript", "Vue.js", "Webpack", "SVG"]
desc = """
browser-based Gallifreyan translator"""
[[project.link]]
name = "check it out"
href = "/gallifreyo"



[[project]]
name = "Maitreya.aic"
date = [[2018–2019]]
tags = ["unfinished"]
tech = ["CoffeeScript", "AngularJS", "CSS"]
desc = """
browser-based text adventure-ish game"""
[[project.link]]
name = "check it out"
href = "/maitreya"



[[project]]
name = "Automafia"
date = [[2016]]
tags = ["abandoned"]
tech = ["JavaScript", "AngularJS"]
desc = """
an attempt to automate Mafia and my first ever programming project"""
[[project.link]]
name = "check it out"
href = "https://theyrecoming.neocities.org/mafia/automafia.html"
