name: frontend build
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/build-client.yml
      - client/**
  pull_request:
    paths:
      - .github/workflows/build-client.yml
      - client/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '15'
        cache: 'npm'
        cache-dependency-path: ${{env.working-directory}}/package-lock.json
    - name: Install
      working-directory: ${{env.working-directory}}
      run: npm install
    - name: Build
      working-directory: ${{env.working-directory}}
      run: npm run build
    - name: Add CNAME
      if: github.ref == 'refs/heads/master'
      working-directory: ${{env.working-directory}}
      run: echo "rossjrw.com" > dist/CNAME
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: ./${{env.working-directory}}/dist
